name: task_manger
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  android_intent_plus: ^6.0.0
  bloc: ^9.0.0
  cloud_firestore: ^6.0.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_storage: ^13.0.1
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_cropper: ^9.1.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  permission_handler: ^12.0.1
  timezone: ^0.10.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - asset/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: asset/Fonts/Poppins-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "asset/images/data.png"
