// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5GU___SzopW6m6BUTmeP-OzDG0YBDZcs',
    appId: '1:622961120008:web:1d1046e678ee60f4d652bd',
    messagingSenderId: '622961120008',
    projectId: 'trackup-2979a',
    authDomain: 'trackup-2979a.firebaseapp.com',
    storageBucket: 'trackup-2979a.firebasestorage.app',
    measurementId: 'G-1PPQ9L75FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3vYUBffgXMquFfM88b8iRNRMlSIt8yDA',
    appId: '1:622961120008:android:6561652bbf467c75d652bd',
    messagingSenderId: '622961120008',
    projectId: 'trackup-2979a',
    storageBucket: 'trackup-2979a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEFSdL20xiGhf429vOVZZ8QQkuyeojkBw',
    appId: '1:622961120008:ios:d19954a75310d39bd652bd',
    messagingSenderId: '622961120008',
    projectId: 'trackup-2979a',
    storageBucket: 'trackup-2979a.firebasestorage.app',
    iosBundleId: 'com.example.taskManger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEFSdL20xiGhf429vOVZZ8QQkuyeojkBw',
    appId: '1:622961120008:ios:d19954a75310d39bd652bd',
    messagingSenderId: '622961120008',
    projectId: 'trackup-2979a',
    storageBucket: 'trackup-2979a.firebasestorage.app',
    iosBundleId: 'com.example.taskManger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5GU___SzopW6m6BUTmeP-OzDG0YBDZcs',
    appId: '1:622961120008:web:6c544e8c441178fad652bd',
    messagingSenderId: '622961120008',
    projectId: 'trackup-2979a',
    authDomain: 'trackup-2979a.firebaseapp.com',
    storageBucket: 'trackup-2979a.firebasestorage.app',
    measurementId: 'G-P99C46JS62',
  );
}
